version: '3.1'

services:
  mongo:
    image: mongo
    container_name: flutter-project
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: flutter-test
      MONGO_INITDB_ROOT_USERNAME: maghwyn
      MONGO_INITDB_ROOT_PASSWORD: u80h98ARs8tZ73FsDAStl1NMH9tpORZOUrEoju4P
    volumes:
      - ./data:/data/db
